import Navbar from "./components/Navbar";
import "./globals.css";
import { Josefin_Sans } from "next/font/google";
import { Providers } from "./providers";
import Footer from "./components/footer";
import Messenger from "./components/messenger";

const josefin = Josefin_Sans({ subsets: ["latin"] });

export const metadata = {
  title: "Xcel",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="dark">
      <body className={josefin.className}>
        <Providers>
          <Messenger />
          <>{children}</>

          <Navbar />
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
